### ISSUE TITLE
Develope a use case/problem statement

### ISSUE THREAD

**Issue by codegirl254** [codegirl254/Data_Analysis_Collaboration#2]

**Comment by derrickroyales** [comment]
The mood around AI; the state of its acceptance and the prospects it boasts

**Comment by derrickroyales** [comment]
> The mood around AI; the state of its acceptance and the prospects it boasts

I reckon this shouldn't matter now since you have already uploaded a dataset
Let me try formulate problem statements from the available data

**Comment by derrickroyales** [comment]
1. The gradient of the change in rates of unemployment per female-youth, female-adults, female-children, male-youth, male-adults, male-children with respect to countries. Hence get the one with the steepest and the one with the gentlest gradient per the above listed categories
2. Max and min for the listed categories with respect to countries
3. Max and min for the years with respect to countries
4. Average rates for the years for the listed categories. From this we can compare the different years with their averages for the listed categories

**Comment by codegirl254** [comment]
Great how about you assign us issues based on what you have mentioned above .Guess we'll be having different jupyter notebook files to perform the tasks.
Remember to fork the repo and your branch.
